apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hello-world-cert
  namespace: example
spec:
  secretName: hello-world-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: hello.danieljsaldana.dev
  dnsNames:
  - hello.danieljsaldana.dev
